apiVersion: v1
kind: Service
metadata:
  name: marsrobot-service
spec:
  type: LoadBalancer
  selector:
    app: marsrobot
  ports:
    - protocol: TCP
      port: 80       # Porta externa para acessar o app
      targetPort: 8080  # Porta no container onde o app está rodando
